import type { RegistryPackage } from '@cpm/types';

/**
 * Fallback packages when registry is unavailable
 * These are the official packages that ship with CPM
 */
export function getFallbackPackages(): RegistryPackage[] {
  return [
    {
      name: '@official/nextjs-rules',
      version: '1.0.0',
      description: 'Next.js 14+ App Router conventions and best practices for Claude Code',
      type: 'rules',
      author: 'cpm',
      downloads: 1250,
      stars: 89,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/nextjs-rules',
      tarball: 'https://github.com/cpm-ai/nextjs-rules/releases/download/v1.0.0/package.tar.gz',
      keywords: ['nextjs', 'react', 'typescript', 'app-router'],
      license: 'MIT',
    },
    {
      name: '@official/typescript-strict',
      version: '1.0.0',
      description: 'TypeScript strict mode best practices and conventions',
      type: 'rules',
      author: 'cpm',
      downloads: 980,
      stars: 67,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/typescript-strict',
      tarball: 'https://github.com/cpm-ai/typescript-strict/releases/download/v1.0.0/package.tar.gz',
      keywords: ['typescript', 'strict', 'types'],
      license: 'MIT',
    },
    {
      name: '@official/react-patterns',
      version: '1.0.0',
      description: 'React component patterns and best practices',
      type: 'rules',
      author: 'cpm',
      downloads: 875,
      stars: 54,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/react-patterns',
      tarball: 'https://github.com/cpm-ai/react-patterns/releases/download/v1.0.0/package.tar.gz',
      keywords: ['react', 'components', 'hooks', 'patterns'],
      license: 'MIT',
    },
    {
      name: '@official/code-review',
      version: '1.0.0',
      description: 'Automated code review skill for Claude Code',
      type: 'skill',
      author: 'cpm',
      downloads: 2100,
      stars: 156,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/code-review',
      tarball: 'https://github.com/cpm-ai/code-review/releases/download/v1.0.0/package.tar.gz',
      keywords: ['code-review', 'quality', 'skill'],
      license: 'MIT',
    },
    {
      name: '@official/git-commit',
      version: '1.0.0',
      description: 'Smart commit message generation skill',
      type: 'skill',
      author: 'cpm',
      downloads: 1800,
      stars: 112,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/git-commit',
      tarball: 'https://github.com/cpm-ai/git-commit/releases/download/v1.0.0/package.tar.gz',
      keywords: ['git', 'commit', 'messages', 'skill'],
      license: 'MIT',
    },
    {
      name: '@official/api-design',
      version: '1.0.0',
      description: 'REST and GraphQL API design conventions',
      type: 'rules',
      author: 'cpm',
      downloads: 650,
      stars: 43,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/api-design',
      tarball: 'https://github.com/cpm-ai/api-design/releases/download/v1.0.0/package.tar.gz',
      keywords: ['api', 'rest', 'graphql', 'design'],
      license: 'MIT',
    },
    {
      name: '@official/testing-patterns',
      version: '1.0.0',
      description: 'Testing best practices for JavaScript/TypeScript projects',
      type: 'rules',
      author: 'cpm',
      downloads: 720,
      stars: 51,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/testing-patterns',
      tarball: 'https://github.com/cpm-ai/testing-patterns/releases/download/v1.0.0/package.tar.gz',
      keywords: ['testing', 'jest', 'vitest', 'patterns'],
      license: 'MIT',
    },
    {
      name: '@official/refactor',
      version: '1.0.0',
      description: 'Code refactoring assistant skill',
      type: 'skill',
      author: 'cpm',
      downloads: 1450,
      stars: 98,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/refactor',
      tarball: 'https://github.com/cpm-ai/refactor/releases/download/v1.0.0/package.tar.gz',
      keywords: ['refactor', 'clean-code', 'skill'],
      license: 'MIT',
    },
    {
      name: '@official/explain',
      version: '1.0.0',
      description: 'Code explanation and documentation skill',
      type: 'skill',
      author: 'cpm',
      downloads: 1320,
      stars: 87,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/explain',
      tarball: 'https://github.com/cpm-ai/explain/releases/download/v1.0.0/package.tar.gz',
      keywords: ['explain', 'documentation', 'skill'],
      license: 'MIT',
    },
    {
      name: '@official/github-mcp',
      version: '1.0.0',
      description: 'GitHub API integration MCP server for Claude Code',
      type: 'mcp',
      author: 'cpm',
      downloads: 890,
      stars: 72,
      verified: true,
      official: true,
      repository: 'https://github.com/cpm-ai/github-mcp',
      tarball: 'https://github.com/cpm-ai/github-mcp/releases/download/v1.0.0/package.tar.gz',
      keywords: ['github', 'mcp', 'api', 'integration'],
      license: 'MIT',
    },
  ];
}
